shout/urls.py
#!/usr/bin/env python
# vim: set fileencoding=utf-8 :
# Created by Andre Anjos <andre.dos.anjos@cern.ch>
# Wed 15 Apr 23:26:54 2009 

from django.conf.urls.defaults import *

urlpatterns = patterns('',
                       url(r'^$', 'shout.views.view_all',
                         name='shout-view'),
                       url(r'^(?P<slug>[\w\.\-]+)/$',
                         'shout.views.view_one', 
                         name='shout-view-one'),
                       url(r'^(?P<slug>[\w\.\-]+)/mail/$',
                         'shout.views.mail', 
                         name='shout-mail'),
                       url(r'^(?P<slug>[\w\.\-]+)/mail/(?P<msgid>[\d]+)/$',
                         'shout.views.mail', 
                         name='shout-mail'),
                       url(r'^mail/(?P<msgid>[\d]+)/$',
                         'shout.views.view_mail', 
                         name='shout-view-mail'),
                       url(r'^(?P<slug>[\w\.\-]+)/subscribe/$',
                         'shout.views.subscribe', 
                         name='shout-subscribe'),
                       url(r'^(?P<slug>[\w\.\-]+)/unsubscribe/$',
                         'shout.views.unsubscribe', 
                         name='shout-unsubscribe'),
                       )

shout/models.py
# vim: set fileencoding=utf-8 :

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.sites.models import Site

class List(models.Model):
  """Represents a list of people that would like to receive announcements"""

  class Meta:
    permissions = ( 
         ('view_list', 'Can view list'), 
         ('email_list', 'Can email to list'), 
                  )

  def __unicode__(self):
    site = Site.objects.get_current()
    return u'%(name)s <%(slug)s@%(site)s>' % \
        {'name':self.name, 'slug': self.slug, 'site': site.domain.split(':')[0]}

  name = models.CharField(_(u'Name'), max_length=256, help_text=_(u'The name of your announcement list'), null=False, blank=False)
  slug = models.SlugField(_(u'Slug'), max_length=64, help_text=_(u'A shorter, slug entry so I can fake e-mails From fields.'), null=False, blank=False, unique=True)
  creation = models.DateTimeField(_(u'Creation'), help_text=_(u'Set here the creation date of your list.'), editable=False, auto_now_add=True)

class Member(models.Model):
  """A person that subscribes to the announcement list"""

  class Meta:
    unique_together = (
          ('email', 'list'),
        )

  def __unicode__(self):
    if self.mobile:
      return u'%(name)s (%(mobile)s) <%(email)s>' % \
          {'name': self.name, 'email': self.email, 'mobile': self.mobile} 
    else:
      return u'%(name)s <%(email)s>' % \
          {'name': self.name, 'email': self.email} 

  name = models.CharField(_(u'Name'), max_length=256, help_text=_(u'Your complete name'), null=False, blank=False)
  email = models.EmailField(_(u'E-mail'), max_length=256, help_text=_(u'Your e-mail'), null=False, blank=False)
  mobile = models.CharField(_(u'Mobile phone number'), max_length=64, help_text=_(u'Your mobile phone number in the format +417X1234567, if you would like to receive SMSs'), null=True, blank=True)
  joined = models.DateTimeField(_(u'Joined'), help_text=_(u'Set here the joining date of this member.'), null=False, blank=False, auto_now_add=True)
  list = models.ForeignKey(List, help_text=_(u'Choose the list this member wants to be associated to'))
  language = models.CharField(_(u'Language'), max_length=6, help_text=_(u'Choose your preferred language. This setting will be used primarily for automatically generated messages.'), null=False, blank=False, default='fr', choices=settings.LANGUAGES)

class Message(models.Model):
  """A message that was sent to a certain list"""

  subject = models.CharField(_(u'Subject'), max_length=256, help_text=_(u'The subject of your message'), null=False, blank=False)
  message = models.TextField(_(u'Message'), help_text=_(u'The body of the message'), null=False, blank=False)
  list = models.ForeignKey(List, help_text=_(u'Choose the list this member wants to be associated to'))
  sent = models.DateTimeField(_(u'Sent'), help_text=_(u'Set here the date of this message.'), null=False, blank=False, auto_now_add=True)
  by = models.ForeignKey(User, help_text=_('The site user that has sent the message'), blank=False, null=False, related_name='message_sender')

shout/templates/shout/email.html
{% extends "base.html" %}
{% load i18n shout_filters %}

{% block media %}
  {{ block.super }}
  <link href="{{ MEDIA_URL }}shout/css/style.css" rel="stylesheet" type="text/css" media="screen" />
{% endblock %}

{% block title %}{% trans "Message" %} "{{ object.subject|truncatewords:4 }}"{% endblock %}

{% block content %}
<div class="post">
  <h2 class="title">{% trans "Message" %} "{{ object.subject|truncatewords:3 }}"</h2>
  <p class="date">{% trans "sent" %}: {{ object.sent|date:"l, j/F/y H:i" }}</p>

  <table class="standard horizontal">
    <tr><th>{% trans "Subject" %}</th><td>{{ object.subject }}</td></tr>
    <tr><th>{% trans "From" %}</th><td>{{ object.by|email_from }}</td></tr>
    <tr><th>{% trans "To" %}</th><td>{{ object.list }}</td></tr>
  </table>

  <h3>{% trans "Message" %}</h3>
  <pre class="message">
  {{ object.message }}
  </pre>
</div>
{% endblock %}

shout/templates/shout/list.html
{% extends "base.html" %}
{% load i18n %}

{% block media %}
  {{ block.super }}
  <link href="{{ MEDIA_URL }}shout/css/style.css" rel="stylesheet" type="text/css" media="screen" />
{% endblock %}

{% block title %}{% trans "Announcement list" %} {{ object.name }}{% endblock %}

{% block content %}
<div class="post">
  <h2 class="title">{% trans "Announcement list" %} "{{ object.name }}"</h2>

  <h3>{% trans "Summary" %}</h3>
  <table class="standard horizontal">
    <tr><th>{% trans "Name" %}</th><td>{{ object.name }}</td></tr>
    <tr><th>{% trans "Slug" %}</th><td>{{ object.slug }}</td></tr>
    <tr><th>{% trans "Date" %}</th><td>{{ object.creation|date:"l, d/M/Y H:i" }}</td></tr>
    <tr><th>{% trans "Members" %}</th><td>{{ object.member_set.count }}</td></tr>
    <tr><th>{% trans "Messages" %}</th><td>{{ object.message_set.count }}</td></tr>
  </table>

  <h3>{% trans "Messages" %}</h3>
  <table class="standard">
    <tr>
      <th>{% trans "Date" %}</th>
      <th>{% trans "Subject" %}</th>
      <th>{% trans "Sender" %}</th>
      <th>{% trans "Actions" %}</th>
    </tr>
    {% for m in object.message_set.all %}
    <tr class="{% cycle "even" "odd" %} standard">
      <td class="sent-date">{{ m.sent|date:"l, j/F/y" }}</td>
      <td class="subject">{{ m.subject }}</td>
      <td class="sender">{{ m.by.first_name }} ({{ m.by.username }})</td>
      <td>
        <a href="{% url shout-view-mail m.id %}"><img src="{{ MEDIA_URL }}shout/img/go-home.png" title="{% trans "view this e-mail" %}" alt="[{% trans "view" %}]"></img></a>
        <a href="{% url shout-mail m.list.slug,m.id %}"><img src="{{ MEDIA_URL }}shout/img/mail-forward.png" title="{% trans "re-send" %}" alt="[{% trans "re-send" %}]"></img></a>
      </td>
    </tr>
    {% endfor %}
  </table>

  <h3>{% trans "Members" %}</h3>
  <table class="standard">
    <tr>
      <th>{% trans "Joined" %}</th>
      <th>{% trans "Name" %}</th>
      <th>{% trans "E-mail" %}</th>
      <th>{% trans "Mobile" %}</th>
    </tr>
    {% for m in object.member_set.all %}
    <tr class="{% cycle "even" "odd" %}">
      <td>{{ m.joined|date:"l, j/F/y" }}</td>
      <td>{{ m.name }}</td>
      <td>{{ m.email }}</td>
      <td>{{ m.mobile }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

shout/templates/shout/lists.html
{% extends "base.html" %}
{% load i18n %}

{% block media %}
  {{ block.super }}
  <link href="{{ MEDIA_URL }}shout/css/style.css" rel="stylesheet" type="text/css" media="screen" />
{% endblock %}

{% block title %}{% trans "Announcement lists" %}{% endblock %}

{% block content %}
<div class="post">
  <h2 class="title">{% trans "Announcement lists" %}</h2>
  <p class="date">{% trans "updated" %}: {% now "d/M/Y" %}</p>

  <p>{% trans "An overview of all announcement lists available in this website. Actions are available to the right of the list name." %}</p>
{% if object_list %}
<table class="shout-lists standard">
  <tr>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Members" %}</th>
    <th>{% trans "Messages" %}</th>
    <th>{% trans "Actions" %}</th>
  </tr>
  {% for o in object_list %}
  <tr class="{% cycle "odd" "even" %}">
    <td>{{ o.name }} ({{ o.slug }})</td>
    <td>{{ o.member_set.count }}</td>
    <td>{{ o.message_set.count }}</td>
    <td>
      <a href="{% url shout-view-one o.slug %}"><img src="{{ MEDIA_URL }}shout/img/go-home.png" title="{% trans "view this announcement list" %}" alt="[{% trans "view" %}]"></img></a>
      <a href="{% url shout-mail o.slug %}"><img src="{{ MEDIA_URL }}shout/img/mail-message-new.png" title="{% trans "e-mail this announcement list" %}" alt="[{% trans "mail" %}]"></img></a>
    </td> 
  </tr>
  {% endfor %}
</table>
{% else %}
<p>{% trans "No announcement lists available yet!" %}</p>
{% endif %}
</div>
{% endblock %}

shout/templates/shout/mail_list.html
{% extends "base.html" %}
{% load i18n shout_filters %}

{% block media %}
  {{ block.super }}
  <link href="{{ MEDIA_URL }}shout/css/style.css" rel="stylesheet" type="text/css" media="screen" />
{% endblock %}

{% block title %}{% trans "Mail to" %} {{ object.name }}{% endblock %}

{% block content %}
<div class="post">
  <h2 class="title">{% trans "Mail to" %} "{{ object.name }}"</h2>

  <h3>{% trans "Write your message" %}</h3>
  <form method="POST" action="">
    <table class="mail-list">
      <tr><th>From</th><td>{{ user|email_from }}</td></tr>
      <tr><th></th><td class="help_text">{% trans "Please note we record who has sent the e-mail, but do not put this information in the message actually sent to the list, in order to protect the sender identity." %}</td></tr>
      <tr><th>To</th><td>{{ object }}</td></tr> 
      <tr><th>Date</th><td>{% now "l, d/M/Y, H:i" %}</td></tr>
      {{ form }} 
      <tr><td><input type="submit" value="{% trans "Send" %}" /></td></tr>
    </table>
  </form>
</div>
{% endblock %}

shout/templates/shout/subscribe.html
{% load i18n %}
<div class="introduction">
<p>{% trans "Subscribe to our list and receive the lastest news about our organisation. The mobile phone number is OPTIONAL" %}:</p>
</div>
<form class="subscription-form" method="POST" action="{% url shout-subscribe "agenda" %}">
<table>
  {{ subscribe_form }}
</table>
<p class="submit"><input type="submit" value="{% trans "subscribe" %}"/></p>
</form>
<div class="unsubscribe">
<p>To unsubscribe <a href="{% url shout-unsubscribe "agenda" %}">click here</a>.</p>
</div>

shout/templates/shout/subscribe_thanks.html
{% extends "base.html" %}
{% load i18n %}

{% block media %}
  {{ block.super }}
  <link href="{{ MEDIA_URL }}shout/css/style.css" rel="stylesheet" type="text/css" media="screen" />
  {{ form.media }}
{% endblock %}

{% block title %}{% trans "Subscription confirmed!" %}{% endblock %}

{% block content %}
<div class="post">
  <h2 class="title">{% trans "Thank you!" %}</h2>
  <p>{% trans "We confirm the subscription of" %} {{ object }} {% trans "to" %} {{ object.list }}. {% trans "Thanks for your interest in our activities. You will hear from us soon!" %}</p>
</div>
{% endblock %}

shout/templates/shout/unsubscribe.html
{% extends "base.html" %}
{% load i18n %}

{% block media %}
  {{ block.super }}
  <link href="{{ MEDIA_URL }}shout/css/style.css" rel="stylesheet" type="text/css" media="screen" />
  {{ form.media }}
{% endblock %}

{% block title %}{% trans "Unsubscribe" %} "{{ object }}{% endblock %}

{% block content %}
<div class="post">
  <h2 class="title">{% trans "Unsubscribe" %} {{ object }}</h2>
  <p>{% blocktrans %}Type-in the subscribed e-mail address at "{{ object }}" to unsubscribe to this announcement list. Please note that by doing this, you also unsubscribe any mobile phone numbers associated (so, no more SMSs from us!).{% endblocktrans %}</p>
  <form method="POST" action="">
  <table class="mail-list">
    {{ form }} 
    <tr><td><input type="submit" value="{% trans "Send" %}" /></td></tr>
  </table>
  </form>
</div>
{% endblock %}

shout/templates/shout/unsubscribe_thanks.html
{% extends "base.html" %}
{% load i18n %}

{% block media %}
  {{ block.super }}
  <link href="{{ MEDIA_URL }}shout/css/style.css" rel="stylesheet" type="text/css" media="screen" />
  {{ form.media }}
{% endblock %}

{% block title %}{% trans "Unsubscription confirmed!" %}{% endblock %}

{% block content %}
<div class="post">
  <h2 class="title">{% trans "Thank you!" %}</h2>
  <p>{% trans "We confirm the unsubscription of" %} {{ object }} {% trans "from" %} {{ object.list }}. {% trans "Thanks for your interest in our activities. You will no longer hear from us." %}</p>
</div>
{% endblock %}